name: Release And Update
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Release Debug APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Download Snapchat APK
        run: wget -q -O snapchat.apk "https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=8253908&key=da7d83e9365b1be9acd1e40f96428e6a81843fa9&forcebaseapk=true"
      
      - name: Download dexsearch and clientlib
        run: |
          wget -q -O dexsearch.jar "https://github.com/rodit/dexsearch/releases/download/v1.0.7/dexsearch-latest.jar"
          wget -q -O app/libs/clientlib.jar "https://github.com/rodit/dexsearch/releases/download/v1.0.7/clientlib-latest.jar"
        
      - name: Download Android Platform
        run: |
          wget -q -O android.zip "https://dl.google.com/android/repository/platform-32_r01.zip"
          unzip -qq android.zip

      - name: Generate Bindings and snapmod jar
        run: java -jar dexsearch.jar -i snapchat.apk -s snap.ds -o bindings.json -j app/libs/snapmod.jar -a "android-12/android.jar" -p xyz.rodit.snapmod.mappings

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Signed Release APK
        run: ./gradlew clean assembleRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Version Info
        run: ./gradlew versionInfo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release APK and Bindings
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/version.json
            bindings.json
